---
name: Test
on: [push]

jobs:
  ruby:
    name: Ruby ${{ matrix.ruby }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        ruby: 
          - "ruby-head"
          - "3.1"
          - "3.0"
          - "2.7"
          - "2.6"
          - "2.5"
          - "2.4"
          - "2.3"
          - "2.2"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Test
        run: bundle exec rake
